#dev
version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
      - '8443:8443'
    volumes:
      - './docker/web/nginx.conf:/etc/nginx/nginx.conf'
      - '.:/var/www/html'
    networks:
      - default
    depends_on:
      - redis
      - app

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#      - '6001:6001' #websocket
    volumes:
      - '.:/var/www/html'
      - './docker/app/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
      - './docker/app/php-fpm.conf:/etc/php/8.1/fpm/php-fpm.conf'
    networks:
      - default
    depends_on:
      - redis
      - mariadb

  redis:
    image: redis:7-alpine
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  mariadb:
    image: mariadb:latest
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - default
    environment:
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
    ports:
      - '127.0.0.1:3306:3306'

networks:
  default:
    driver: bridge

volumes:
  redis:
    driver: local
  mariadb:
    driver: local
