#dev
services:
    web:
        image: nginx:latest
        ports:
            - "8080:8080"
            - "8443:8443"
        volumes:
            - "./docker/web/nginx.conf:/etc/nginx/nginx.conf"
            - ".:/var/www/html"
        networks:
            - default
        depends_on:
            - redis
            - app

    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        #      - '6001:6001' #websocket
        volumes:
            - ".:/var/www/html"
            - "./docker/app/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
            - "./docker/app/php-fpm.conf:/etc/php/8.1/fpm/php-fpm.conf"
            - "./storage:/var/www/html/storage"
            - "./bootstrap/cache:/var/www/html/bootstrap/cache"
        networks:
            - default
        depends_on:
            - redis
            - mariadb

    redis:
        image: redis:7-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "redis:/data"
        networks:
            - default
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mariadb:
        image: mariadb:latest
        volumes:
            - "mariadb:/var/lib/mysql"
        networks:
            - default
        ports:
            - "3306:3306"
        environment:
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"

networks:
    default:
        driver: bridge

volumes:
    redis:
        driver: local
    mariadb:
        driver: local
